syntax = "proto3";

package gsamd;

message StaticSamFile {
  uint32 version = 1;
  bool use_gsam = 2;
  bool use_small_dict = 3;
  int64 n_predicts = 4;
  double alpha = 5;
  int64 k = 6;
  repeated int64 input_ids = 7 [packed = true];
  repeated int64 boundary_end = 8 [packed = true];
  repeated State states = 9;
}

message State {
  int64 link = 1;
  int64 length = 2;
  int64 cnt_endpos = 3;
  int64 min_endpos = 4;
  repeated Edge edge = 5;
  repeated Edge topk_edge = 6;
}

message Edge {
  int64 token = 1;
  int64 state = 2;
}
